CREATE DATABASE IF NOT EXISTS cdek;
GRANT ALL PRIVILEGES ON cdek.* TO pc@localhost IDENTIFIED BY 'pc';

USE cdek;

CREATE TABLE IF NOT EXISTS entity (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30),
  INDEX(name)
) engine=InnoDB;